### ISSUE TITLE
Microsoft Auth Issue

### ISSUE THREAD

**Issue by prkvm** [tropicbliss/buckshot#1]
Hello again! I have been using node sniper for 2 weeks before this one and everyone was ok with auth. But now im getting only refresh token on the auth site (check ss) Idk how to fix cuz i cant find cookies of this website
![image](https://user-images.githubusercontent.com/73988148/118523279-a8598e80-b745-11eb-9f80-ca46dba19b8e.png)

**Comment by prkvm** [comment]
I tried deleting cookies of this website but nothing works anyway

**Comment by tropicbliss** [comment]
This is intentional. Download the latest version (which is v0.4.0). When you reach this page copy this instead of the access token. It contains info about both the access and refresh token if you scroll far enough to the right. The sniper will automatically extract the necessary info from this json string.

**Comment by prkvm** [comment]
ok thanks
